### ISSUE TITLE
DHooks error (Hook type not supported)

### ISSUE THREAD

**Issue by vintagepc** [Scags/TF2Classic-Tools#3]
Running on SM1.10 with dhooks-2.2.0 detour14a, cannot get tf2c.smx to load, it fails with this error:
-> sm plugins load tf2c
L 08/02/2020 - 19:52:27: [SM] Exception reported: Hook type not supported on this game
L 08/02/2020 - 19:52:27: [SM] Blaming: tf2c.smx
L 08/02/2020 - 19:52:27: [SM] Call stack trace:
L 08/02/2020 - 19:52:27: [SM]   [0] SDKHook
L 08/02/2020 - 19:52:27: [SM]   [1] Line 233, C:\Users\johnm\OneDrive\Documents\GitHub\TF2Classic-Tools\sourcemod\scripting\tf2c.sp::OnClientPutInServer
L 08/02/2020 - 19:52:27: [SM]   [2] Line 211, C:\Users\johnm\OneDrive\Documents\GitHub\TF2Classic-Tools\sourcemod\scripting\tf2c.sp::OnPluginStart
[SM] Plugin tf2c.smx failed to load: Error detected in plugin startup (see error logs).

Is there a particular dhooks extension that is required?

**Comment by Scags** [comment]
Have you extracted the [base SourceMod gamedata](https://github.com/Scags/TF2Classic-Tools/tree/master/sourcemod/gamedata) too? The tools plugin does rely on a few things that SourceMod does not support directly. That error is in SDKHooks, not DHooks. Closely named but entirely separate haha.

**Comment by vintagepc** [comment]
Looks like that was it, missed one of 'em. Thanks!
