### ISSUE TITLE
Could not load native for "TF2_RemoveCondition"

### ISSUE THREAD

**Issue by vintagepc** [Scags/TF2Classic-Tools#5]
Noticed this in the logs today - though I believe it was loading without errors before. 
Any thoughts where I should start digging?

L 10/04/2020 - 21:28:39: [tf2c.smx] Could not load native for "TF2_RemoveCondition"
L 10/04/2020 - 21:28:39: [tf2c.smx] Could not set RemoveCondition from config!
L 10/04/2020 - 21:28:39: [SM] Exception reported: Hook not setup for a detour.
L 10/04/2020 - 21:28:39: [SM] Blaming: tf2c.smx
L 10/04/2020 - 21:28:39: [SM] Call stack trace:
L 10/04/2020 - 21:28:39: [SM]   [0] DHookEnableDetour
L 10/04/2020 - 21:28:39: [SM]   [1] Line 170, C:\Users\johnm\OneDrive\Documents\GitHub\TF2Classic-Tools\sourcemod\scripting\tf2c.sp::OnPluginStart
L 10/04/2020 - 21:28:39: [SM] Unable to load plugin "tf2c.smx": Error detected in plugin startup (see error logs)

**Comment by Scags** [comment]
Did TF2Classic have an update recently? If not, the [latest gamedata file](https://github.com/Scags/TF2Classic-Tools/blob/master/sourcemod/gamedata/tf2c.txt) should have the proper gamedata.

**Comment by vintagepc** [comment]
Maybe that was it, I'll give it a try. SM's auto gamedata updating has spoiled us. ;-)

**Comment by vintagepc** [comment]
Derp, again. :facepalm:
