### ISSUE TITLE
Entity Outputs disabled?

### ISSUE THREAD

**Issue by vintagepc** [Scags/TF2Classic-Tools#8]
Hi - forgive my ignorance if this isn't related to tf2c-tools; some searching seemed to suggest it was gamedata related though and that it requires a signature for SDKTools

Anyway, I'm trying to use a plugin that calls HookEntityOutput() but on load I get an error:

` [SM] Exception reported: Entity Outputs are disabled - see error logs for details`. 

Is that something that can be resolved with TF2C? I don't think I saw this issue prior to 2.0.2 and the gamedata for tf2classic-tools should be up to date.

**Comment by vintagepc** [comment]
Update - this looks like a bad funcsig for Linux:  Came across this in the logs:

`[SDKTOOLS] Sigscan for FireOutput failed`

**Comment by Scags** [comment]
Updated with most recent commit. Sorry about that, been busy recently.

**Comment by vintagepc** [comment]
Can confirm this fixed it and Detour is now happy
