### ISSUE TITLE
Can't seem to spawn in with this plugin and requirements installed

### ISSUE THREAD

**Issue by AnnoyingGuide** [Scags/TF2Classic-Tools#9]
Hi, currently I can't for the life of me get this to work although I can't really pinpoint the problem plugin either seems like dhooks which is a requirement that has been crashing the game when I try to spawn with this error [DHOOKS] FATAL: Failed to find return address of original function. Check the arguments and return type of your detour setup. If you have any idea how to fix this that would be greatly appreciated. or maybe the most reason update to tf2classic borked it.

**Comment by Scags** [comment]
Either A: your gamedata is outdated. Make sure you have the latest file in the gamedata folder. Or B: you are running an older version of DHooks. Make sure you are running the latest version of that,

**Comment by AnnoyingGuide** [comment]
I did update both from their latest release and even reinstalled sourcemod and such, but I'm still getting this crash. Maybe I'm using the wrong version of dhooks? Where do you get the version you used for this? as this version doesn't work https://github.com/peace-maker/DHooks2/releases/tag/v2.2.0-detours17

**Comment by whysodrooled** [comment]
Looks like the problem is related to SetInWaitingForPlayers, Weird for me since I can't see the problem. Any updates to this would be appreciated.
For now, it only works if I comment out codes for the SetInWaitingForPlayers hook in OnPluginStart. (line 183~189)
